prepare:
  test_size: 0.2
  random_state: 42

train:
  random_state: 42
  models:
    linear_regression: {}
    ridge:
      alpha: 1.0
    random_forest:
      n_estimators: 100
      max_depth: 10

# Settings for scripts/run_experiments.py (HW3)
experiments:
  experiment_name: "boston-housing-hw3"
  val_size: 0.2
  random_state: 42
